### ISSUE TITLE
Text color question

### ISSUE THREAD

**Issue by ColtonIdle** [mienaikage/fish-theme-dracula#12]
Just installed and it seems to work great. Bad commands are red. Good commands in a light blue. But I was wondering if I should be seeing white as output after a command runs.

e.g. Type in `pwd` and it'll show you white text (dont mind the reversed screenshot sorry)
<img width="132" alt="Screen Shot 2020-12-11 at 5 30 02 PM" src="https://user-images.githubusercontent.com/31751141/101960905-8415e680-3bd6-11eb-9d64-97c18e3b0bf8.png">

**Comment by jaminthorns** [comment]
Since this theme is just a script that modifies the `fish_color_*` variables, it has no effect on the output of commands. It controls the colors of text when typing inside the prompt. The color of text after you enter a command is entirely up to that command, and `fish` can't do anything to control that.

In general, when a command line program outputs text, it will be rendered as the foreground color. If that program wants to output colored text, it can do so with [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors). Additionally, there are ways to render full colors. The `fish` shell (along with this theme) has no control over how the foreground, background, and ANSI colors are rendered. That is the job of a _terminal_, not a _shell_. You can visit the [Dracula theme website](https://draculatheme.com/) to see if the terminal you use has a theme available.

**Comment by ColtonIdle** [comment]
@jaminthorns thank you for the detailed reply. I learned something new! Thank YOU!!!!!!!!
