### ISSUE TITLE
need help to use Dracula/Fish shell theme 

### ISSUE THREAD

**Issue by ghost** [mienaikage/fish-theme-dracula#15]
>i have git clone fish-master in /opt/Theme/fish  then link | copy to **~/.confg/fish/conf.d/dracula.fish**
> and then restart my **$SHELL** -> _fish shell_ 
but not working i am on Arch Linux with qtile WM and [ alacritty ] Terminal 
can you guid me

**Comment by kseistrup** [comment]
@sky01js

You should also install the Dracula theme for `alacritty`: https://draculatheme.com/alacritty

And if you are running X.org (rather than Wayland), you _may_ want to install the Dracula themed Xresources: https://draculatheme.com/xresources

**Comment by jaminthorns** [comment]
@sky01js I did notice a typo in the path you linked/copied to, you were missing an `i`, so the path to copy the theme to should be `~/.config/fish/conf.d/dracula.fish`.

It's important to note that the Dracula for Fish theme only provides syntax highlighting for the text that you type within the shell, it won't change the colors for your prompt. If you're wanting text that uses [ANSI codes](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) (your prompt is most likely using these) to be Dracula-themed, then you'll also need to install a theme for your terminal. Since you use Alacritty, the theme @kseistrup linked should work.

If you're still having issues, could you please post your `~/.config/fish/config.fish` file and share a screenshot of your terminal?

**Comment by ghost** [comment]
Thanks for your time and Replaying 

I have already installed all of these as shown in SS 
![image](https://user-images.githubusercontent.com/96027036/149642220-cf33b2c0-8a05-4709-98d9-f9e4ae6f8227.png)

@jaminthorns here my SS of 
![image](https://user-images.githubusercontent.com/96027036/149642296-54b699fa-4362-4a4a-888e-2de91e46d83b.png)

![image](https://user-images.githubusercontent.com/96027036/149642308-6523f5c9-8a57-41b5-b18f-5c11b30942b1.png)

@kseistrup  I have installed Alacritty Dracula theme as shown SS  

![image](https://user-images.githubusercontent.com/96027036/149642327-99d3bb4d-3851-40c2-ba88-cf146779ffcd.png)
![image](https://user-images.githubusercontent.com/96027036/149642341-28687223-36c6-4206-9aa0-b29f5f815f08.png)

regard:
sky

**Comment by jaminthorns** [comment]
@sky01js I can tell from your screenshot that you have the Dracula for Fish theme installed. The command is [cyan](https://spec.draculatheme.com/#Cyan) and the filename is [purple](https://spec.draculatheme.com/#Purple). I explained in my previous message that this theme doesn't affect your prompt. Closing this issue.
